/* eslint-disable react/jsx-key */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react/jsx-no-target-blank */
/* eslint-disable @next/next/no-img-element */
import React from "react";
import ScrollOut from "scroll-out";
import { useState, useEffect, useRef } from "react";

import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Footer from "../components/Footer";

import styles from "../styles/Index.module.scss";

//image import

import logo from "../public/logo.png";

import Banner from "../sections/banner";
import About from "../sections/About";
import OurSecret from "../sections/Our-Secret";
import Video from "../sections/Video";
import Reviews from "../sections/Reviews";
import Contact from "../sections/contact";
import Product from "../sections/Product";

export default function Home() {
  useEffect(() => {
    ScrollOut({
      /* options */
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Care</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <div className="loader_overlay">
        <div className="container">
          <img src={logo.src} alt="loader logo" />
        </div>
      </div> */}
      <main className={styles.main}>
        <Banner />
        <About />
        <OurSecret />
        <Video />
        <Product />
        <Reviews />
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
